/**
 * generate-metrics.mjs
 *
 * Reads the per-repo metrics JSON files written by fetch-metrics.mjs and
 * generates docs/metrics.md — a VitePress page with a summary table and
 * per-repo language breakdown.
 *
 * The tokei field in each metrics.json is a flat object keyed by language
 * name, where each value has { code, blanks, comments } aggregates.
 */

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../../");
const METRICS_DIR = path.join(ROOT, "docs/public/metrics");
const OUT_FILE = path.join(ROOT, "docs/metrics.md");

function repoLink(repo) {
  return `[${repo}](https://github.com/anolishq/${repo})`;
}

function formatNumber(n) {
  return n.toLocaleString("en-US");
}

// Tokei includes a "Total" synthetic key — exclude it from per-language tables.
const TOKEI_EXCLUDED = new Set(["Total"]);

/** Return sorted array of { lang, code } from tokei object. */
function langBreakdown(tokei) {
  if (!tokei || typeof tokei !== "object") return [];
  return Object.entries(tokei)
    .filter(([lang]) => !TOKEI_EXCLUDED.has(lang))
    .map(([lang, stats]) => ({ lang, code: stats.code ?? 0 }))
    .filter((e) => e.code > 0)
    .sort((a, b) => b.code - a.code);
}

/** Render a language breakdown table. */
function langTable(langs) {
  if (langs.length === 0) return "_No language data available._";
  const rows = langs.map(
    ({ lang, code }) => `| ${lang} | ${formatNumber(code)} |`
  );
  return ["| Language | Lines of Code |", "|---|---:|", ...rows].join("\n");
}

const manifest = JSON.parse(
  await fs.readFile(path.join(METRICS_DIR, "_manifest.json"), "utf-8")
);

const repoMetrics = [];

for (const { repo, tag } of manifest.repos) {
  const filePath = path.join(METRICS_DIR, `${repo}.json`);
  const data = JSON.parse(await fs.readFile(filePath, "utf-8"));

  const langs = langBreakdown(data.tokei);
  const totalCode = langs.reduce((s, l) => s + l.code, 0);
  const top3 = langs.slice(0, 3).map((l) => l.lang);

  repoMetrics.push({
    repo,
    tag: data.tag ?? tag,
    sha: data.sha ?? "",
    collected_at: data.collected_at ?? "",
    langs,
    totalCode,
    top3,
  });
}

// ── Summary table ──────────────────────────────────────────────────────────

const summaryHeader = [
  "| Repo | Latest Release | Total LoC | Top Languages |",
  "|---|---|---:|---|",
];
const summaryRows = repoMetrics.map(({ repo, tag, totalCode, top3 }) => {
  const tagLink = `[${tag}](https://github.com/anolishq/${repo}/releases/tag/${tag})`;
  return `| ${repoLink(repo)} | ${tagLink} | ${formatNumber(totalCode)} | ${top3.join(", ") || "—"} |`;
});

const summaryTable = [...summaryHeader, ...summaryRows].join("\n");

// ── Per-repo details ───────────────────────────────────────────────────────

const details = repoMetrics
  .map(({ repo, tag, sha, collected_at, langs, totalCode }) => {
    const shaSnippet = sha ? sha.slice(0, 7) : "";
    const shaDisplay = shaSnippet
      ? ` ([\`${shaSnippet}\`](https://github.com/anolishq/${repo}/commit/${sha}))`
      : "";
    const collectedDisplay = collected_at
      ? ` — collected ${collected_at.replace("T", " ").replace("Z", " UTC")}`
      : "";

    return [
      `### ${repo}`,
      "",
      `**Release**: [${tag}](https://github.com/anolishq/${repo}/releases/tag/${tag})${shaDisplay}${collectedDisplay}`,
      "",
      langTable(langs),
      "",
      `**Total**: ${formatNumber(totalCode)} lines of code across ${langs.length} language${langs.length !== 1 ? "s" : ""}.`,
      "",
    ].join("\n");
  })
  .join("\n");

// ── Assemble page ──────────────────────────────────────────────────────────

const generatedAt = manifest.fetched_at
  ? manifest.fetched_at.replace("T", " ").replace(/\.\d+Z$/, " UTC")
  : new Date().toISOString();

const page = [
  "---",
  "# This file is generated by scripts/generate-metrics.mjs — do not edit.",
  "---",
  "",
  "# Org Metrics",
  "",
  "Code metrics for all active anolishq repositories, sourced from the `metrics.json`",
  "release asset published with each tagged release.",
  "",
  `_Last updated: ${generatedAt}_`,
  "",
  "## Summary",
  "",
  summaryTable,
  "",
  "## Details",
  "",
  details,
].join("\n");

await fs.writeFile(OUT_FILE, page);
console.log(`Generated ${OUT_FILE} (${repoMetrics.length} repos).`);
